src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 *
 * Events hasn't change since first day, (maybe) their details should be in code instead of bdd
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $bbch_code;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_observable;

    const DISPLAY_LABELS = [
        'feuillaison' => 'Feuillaison',
        'floraison' => 'Floraison',
        'fructification' => 'Fructification',
        'sénescence' => 'Sénescence',
        '1ère apparition' => '1ère apparition',
    ];

    const CSS_CLASSES = [
        'feuillaison' => 'feuillaison',
        'floraison' => 'floraison',
        'fructification' => 'fructification',
        'sénescence' => 'senescence',
        '1ère apparition' => 'apparition',
    ];

    const ANIMALS_EVENT = '1ère apparition';

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStadeBbch(): ?int
    {
        return $this->bbch_code;
    }

    public function setStadeBbch(?int $bbch_code): self
    {
        $this->bbch_code = $bbch_code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsObservable(): ?bool
    {
        return $this->is_observable;
    }

    public function setIsObservable(?bool $is_observable): self
    {
        $this->is_observable = $is_observable;

        return $this;
    }
}

src/Entity/Species.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SpeciesRepository")
 *
 * Species list doesn't vary often, maybe their details should be in code instead of bdd
 */
class Species
{
    const TREE_GROUPS = [
        'Abricotier',
        'Amandier',
        'Cerisier',
        'Poirier',
        'Pommier',
        'Prunier',
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vernacular_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $scientific_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeSpecies")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Post")
     * @ORM\JoinColumn(nullable=true)
     */
    private $post;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVernacularName(): ?string
    {
        return $this->vernacular_name;
    }

    public function setVernacularName(string $vernacular_name): self
    {
        $this->vernacular_name = $vernacular_name;

        return $this;
    }

    public function getScientificName(): ?string
    {
        return $this->scientific_name;
    }

    public function setScientificName(string $scientific_name): self
    {
        $this->scientific_name = $scientific_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): TypeSpecies
    {
        return $this->type;
    }

    public function setType(TypeSpecies $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function isTreeGroup()
    {
        $vernacularNameParts = explode(' ', $this->getVernacularName());

        return in_array($vernacularNameParts[0], self::TREE_GROUPS);
    }
}

templates/pages/a-propos.html.twig
{% extends 'base.html.twig' %}

{% block main_content %}

	{% include 'layout/header.html.twig' with ({
        'title': 'À propos de l’Observatoire des saisons',
        'subtitle': 'Participez au programme de <strong>l’ODS</strong>.'
    }) %}

    <div class="rich-text-block page-content">
        {{ page.content|default|raw }}
    </div>

{% endblock %}

templates/pages/apropos.html.twig
{% extends 'base.html.twig' %}

{% block main_content %}

	{% include 'layout/header.html.twig' with ({
        'title': 'À propos de l’Observatoire des saisons',
        'subtitle': 'Participez au programme de <strong>l’ODS</strong>.'
    }) %}

{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block main_content %}

    {% include 'layout/header.html.twig' with ({
        'title': 'Contactez-nous',
        'subtitle': 'Vous pouvez nous contacter à l’adresse <a href="mailto:contact@obs-saisons.fr">contact@obs-saisons.fr</a> ou via le formulaire ci-dessous&nbsp;:'
    }) %}

    {% include 'forms/contact/contact-form.html.twig' with ({
        'form':form,
        'action': 'contact',
        'isPage': true,
        'user':app.user
    }) %}

{% endblock %}

templates/pages/homepage.html.twig
{% extends 'base.html.twig' %}
{% block content %}
	{% if lastNewsPosts[0] %}
		<div class="actus-une">
			{% for lastNewsPost in lastNewsPosts %}
				<div class="actus-une-img {{ not loop.first ? 'hidden' }}" style="background-image: url({{ lastNewsPost.cover }});"></div>
			{% endfor %}
			<div class="actus-une-content">
				<div class="content-narrow-header bottom-div">
					<h4 class="content-narrow-title">Actualités</h4>
					{% include 'components/buttons/nav-arrow-buttons.html.twig' with {arrows:{
						'target': 'actu-une-container',
						'directions': ['prev', 'next'],
						'isInactive': 2 > lastNewsPosts|length
					}} %}
				</div>
				{% for lastNewsPost in lastNewsPosts %}
					<a href="{{ path("news_post_single_show", {'slug': lastNewsPost.slug}) }}" class="actu-une-container {{ not loop.first ? 'hidden' }}">
						<h4 class="actus-une-title">{{ lastNewsPost.title }}</h4>
						<div class="actus-une-date">{{ lastNewsPost.createdAt|format_datetime(pattern='d MMMM Y',locale='fr') }}</div>
					</a>
				{% endfor %}
				{% include 'components/buttons/full-block-width-button.html.twig' with {button_path: 'news_posts_list', button_label: 'toutes les actualités'}%}
			</div>
			{% if is_granted("ROLE_USER") %}
				<div class="actionbar mb-0 mx-0 px-2 actionbarHomePage">
					<a href="{{ path('news_post_create') }}" class="squared-button add-circle-icon buttonHomePage">
						<div class="squared-button-label buttonLabelNews">ajouter
						</div>
					</a>
				</div>
			{% endif %}
		</div>
	{% else %}
		<div class="actus-une">
			<div class="actus-une-img" style="background-image: url({{ asset('media/layout/planet-grid-leaf.svg') }});background-position: 50% 50%;background-size: 50%"></div>
			<div class="actus-une-content">
				<div class="content-narrow-header bottom-div">
					<h4 class="content-narrow-title">Actualités</h4>
				</div>
				<div class="actus-une-title">Pas encore d’actualités</div>
			</div>
		</div>
	{% endif %}

	<div class="content home">

		<div class="content-une-block">
			<img src="{{ asset('media/layout/Fichier 3.svg') }}" alt="" class="content-block-img" height="50">
			<div class="content-block-infos">
				<h3 class="content-narrow-title dark">Comment participer ?</h3>
				<h4 class="content-blocks-title">En quelques minutes, devenez un observateur des Saisons !</h4>
				<p class="content-blocks-text">Pour participer à l’Observatoire des Saisons, il vous suffit de suivre 3 étapes : prendre connaissance du protocole d’observation, choisir des espèces à observer et saisir vos observations phénologiques !</p>
				<a href="{{ path('participer') }}" class="content-block-link">
					<div class="home-link">En savoir plus</div>
				</a>
			</div>
		</div>
		{% if lastEventPosts[0] %}
			<div class="next-event">
				<div class="content-narrow-header bottom-div">
					<h4 class="content-narrow-title orange">Évènements</h4>
					{% include 'components/buttons/nav-arrow-buttons.html.twig' with {arrows: {
						'target': 'next-event-container',
						'directions':['prev','next'],
						'arrow_color': 'orange',
						'borders': 'light',
						'isInactive': 2 > lastNewsPosts|length
					}} %}
				</div>
				{% for lastEventPost in lastEventPosts %}
					<a href="{{ path("event_post_single_show", {'slug': lastEventPost.slug}) }}" class="next-event-container {{ not loop.first ? 'hidden' }}">
						<div class="next-event-descr">{{ lastEventPost.title }}</div>
						<div>
							<h5 class="next-event-title">{{ eventDatesDisplay(lastEventPost.startDate,lastEventPost.endDate) }}</h5>
							<div class="next-event-city">{{ lastEventPost.location }}</div>
						</div>
					</a>
				{% endfor %}
				{% include 'components/buttons/full-block-width-button.html.twig' with {button_path: 'event_posts_list', button_label: 'tous les évènements', button_color: 'orange'} %}
				{% if is_granted("ROLE_USER") %}
					<div class="actionbar mb-0 mx-0 px-2 actionbarHomePage">
						<a href="{{ path('event_post_create') }}" class="squared-button add-circle-icon buttonHomePage">
							<div class="squared-button-label buttonLabelEvent">
								ajouter
							</div>
						</a>
					</div>
				{% endif %}

			</div>
		{% else %}
			<div class="next-event">
				<div class="content-narrow-header bottom-div">
					<h4 class="content-narrow-title orange">Évènements</h4>
				</div>
				<div class="next-event-descr">Pas d'évènements annoncés en ce moment</div>
			</div>

		{% endif %}

	</div>
	<div class="content home">
		{% if featuredSpecies is not empty %}
			{% for id,eventSpecies in featuredSpecies %}
				{% include 'components/featuredSpecies.html.twig' %}
			{% endfor %}
		{% else %}
			<div class="now featured-species species" style="background-image: url({{ asset('/media/layout/winter.svg')}});background-size: contain;">
				<div class="content-block-infos horiz">
					<div class="infos-insert">
						<h3 class="content-narrow-title">à Observer en ce moment</h3>
						<h4 class="content-blocks-title small">Bientôt de nouvelles espèces à observer</h4>
					</div>
				</div>
			</div>
		{% endif %}
		<div class="recent-obs">
			<div class="content-narrow-header obs">
				<h4 class="content-narrow-title dark">Observations récentes</h4>
			</div>
			<ul class="ods-list-unstyled">
				{% for obs in lastObservations %}
					{% set obsIndividual = obs.individual %}
					{% set obsSpecies = obsIndividual.species %}
					{% set obsEvent = obs.event %}
					{% set obsUser = obs.user %}
					<li>
						<a href="{{ path('stations_show', {'slug': obsIndividual.station.slug }) }}#{{ obsSpecies.vernacularName|slugify }}" class="recent-obs-item">
							<img src="/media/species/{{ obsSpecies.picture }}{{ obsSpecies.type.id == 1 ? "_#{obsEvent.stadeBbch|first}" }}.jpg" alt="{{ obsSpecies.vernacularName|capitalize }} - {{ obs.user.name|upper }} - {{ obs.date|date('d/m/Y') }}" width="80">
							<div class="recent-obs-item-content first">
								<div class="recent-obs-title">{{ obsSpecies.vernacularName|capitalize }}</div>
								<div class="recent-obs-item-stage">{{ obsEvent.name|capitalize }} {{ obsEvent.stadeBbch != null ? "stade #{obsEvent.stadeBbch}" }}</div>
								<div class="recent-obs-item-stage">{{ obsUser.name }}</div>
							</div>
						</a>
					</li>
				{% endfor %}
			</ul>
			{% if app.user %}
				{% include 'components/buttons/full-block-width-button.html.twig' with {button_path: 'my_stations', button_label: 'ajoutez une observation'} %}
			{% else %}
				{% include 'components/buttons/full-block-width-button.html.twig' with {button_path: 'participer', button_label: 'comment participer'} %}
			{% endif %}
		</div>
	</div>
	<div class="number-obs-container">
		<div class="banner-number">
			<div class="number-obs-infos">
				<div class="number-obs">{{ obsCount }}</div>
				<div class="number-obs-period">Observation{{ obsCount > 1 ? 's' }} en {{ "now"|date("Y") }}</div>
			</div>
			<div class="mosaic">
				{% for i in 0..3 %}
					<div style="background-image: url('{{ lastObservationsWithImages[i].picture|default }}');"></div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

templates/pages/resultats-carte-calendriers.html.twig
{% extends 'base.html.twig' %}

{% block main_content %}

    <div class="rich-text-block">
        {{ page.content|default|raw }}
    </div>

    {% include 'layout/header.html.twig' with ({
        'title': 'Carte des résultats',
        'subtitle': "Cartes et graphiques dynamiques qui vous permettent d’explorer et visualiser les données en temps réel de l’Observatoire des Saisons.<br>
                     <a href=#{path('export')} target=#'_blank' download>Exportez les données de l’Observatoire des Saisons</a>."
    }) %}

    <div class="criteria-container">
        <select name="type-species" id="type-species" class="criteria-list">
            <option value="0" selected class="default-criteria">Tous les types d’espèces</option>
            {% for typeSpecies in allTypeSpecies %}
                <option value="{{ typeSpecies.id }}">{{ typeSpecies.name|capitalize }}</option>
            {% endfor %}
        </select>

        <select name="species" id="species" class="criteria-list" data-selected-type-species="0">
            <option value="0" selected class="default-criteria">Toutes les espèces</option>
            {% for species in allSpecies %}
                <option
                        value="{{ species.id }}"
                        data-events-ids="{{ speciesEvents[species.id] }}"
                        data-type-species-id="{{ species.type.id }}"
                        hidden disabled
                >
                    {{ species.vernacularName }}
                </option>
            {% endfor %}
        </select>

        <select name="events" id="events" class="criteria-list">
            <option value="0" selected class="default-criteria">Tous les évènements</option>
            {% for event in events %}
                <option value="{{ event.id }}">{{ event.name|capitalize }} {{ event.stadeBbch }}</option>
            {% endfor %}
        </select>

        <select name="year" id="year" class="criteria-list">
            {% for i in minYear..'now'|date('Y') %}
                <option value="{{ i }}"{% if loop.last %} selected{% endif %}>{{ i }}</option>
            {% endfor %}
        </select>
        {% set month = 'now'|date('m') - 1%}
        <div class="slidecontainer">
            <input type="range" min="0" max="12" class="slider" value="{{month}}" id="myRange">
            <output><span id="demo"></span></output>
        </div>
        <select name="region" id="region" class="criteria-list">
            <option value="0">Toutes les régions</option>
            {% for id, region in regions %}
                <option value="{{ id }}">{{ region }}</option>
            {% endfor %}
        </select>

        <select name="department" id="department" class="criteria-list">
            <option value="0">Tous les départements</option>
            {% for id, department in departments %}
                <option value="{{ id }}">{{ department }}</option>
            {% endfor %}
        </select>
        <label>
            <input id="cumul" type="checkbox" checked>
            Cumul depuis le début de l'année
        </label>

    </div>

    <div id="results-map" class="result-map"></div>

    <script>
        let dataRoute = "{{ path('export_filtered')|escape('js') }}";
        let stationUrlTemplate = "{{ path('stations_show', {slug: 'slugPlaceHolder'})|escape('js') }}";
    </script>
        {% include 'layout/header.html.twig' with ({
            'title': 'Observation des espèces au cours des années',
            'subtitle': 'Ces graphiques représentent les données brutes saisies par les observateur.rice.s.'
        }) %}
        <div id='allDataChart' class="container mt-5" id="observation-calendar-chart">
        
            <div class="mb-3 selectMultiple" id="selectMultiple" data-placeholder="Select species">
                <label for="species" class="form-label">Filtrer par espèces</label>
                    <select name="species[]" id="species-calendar-chart" class="form-select criteria-list" multiple>
                        {% for specie in allSpecies %}
                            <option value="{{ specie.id }}" {% if specie.id in selectedSpeciesIds %}selected{% endif %}>
                                {{ specie.vernacularName }}
                            </option>
                        {% endfor %}
                    </select>
            </div>
            <div class="mb-3 selectMultiple" id="selectMultiple-stade" data-placeholder="Select event">
                <label for="event" class="form-label">Filtrer par stade</label>
                <div>
                    <select class="form-select criteria-list" name="event[]" multiple id="event-calendar-chart">
                        <option value="0">Tous stades</option>
                        {% for event in events %}
                            <option value="{{ event.id }}" {% if event.id in selectedEventId %}selected{% endif %}>
                                {{ event.name }}{% if event.stadeBbch is not empty %} - {{ event.stadeBbch }}{% endif %}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="mb-3 selectMultiple" id="selectMultiple-year" data-placeholder="Select year">
                <label for="year" class="form-label">Filtrer par année</label>
                <div>
                    <select class="form-select criteria-list" name="year[]" multiple id="year-calendar-chart">
                        <option value="1">Toutes les années</option>
                        {% for i in minYear..'now'|date('Y') %}
                            <option value="{{ i }}"{% if i in selectedYear %} selected{% endif %}>{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            {% if observations is empty %}
                <div id="alerteCalendar" class="alert alert-danger">
                    Aucune donnée pour les critères demandés, veuillez modifier au moins un de vos critères
                </div>
            {% endif %}
            <div id="combinedYearChart" class="mt-5"></div>
            <div id="combinedSelectedYearChart" class="mt-5"></div>
        </div>
    <script>
        let calendarRoute = "{{ path('calender_data')|escape('js') }}";
    </script>
    <div id="multipleChart" class="mt-5"></div>

    {% include 'layout/header.html.twig' with ({
        'title': 'Histogramme des différents stades par espèce'
    }) %}

    <div id="phenological-chart-container">
        <select name="species" id="species-phenological-chart" class="criteria-list">
            <option value="0" class="default-criteria" selected>Toutes les espèces</option>
            {% set species_id = null %}
            {% for species in allSpecies %}
                <option value="{{ species.id }}">
                    {{ species.vernacularName }}
                {% set species_id = species.id %}
                </option>
            {% endfor %}
        </select>

        <select name="year" id="year-phenological-chart" class="criteria-list">
            <option value="0">Toutes les années</option>
            {% set year = null %}
            {% for i in minYear..'now'|date('Y') %}*
                <option value="{{ i }}">{{ i }}</option>
                {% set year = i %}
            {% endfor %}
        </select>

        <select name="region" id="region-phenological-chart" class="criteria-list">
            <option value="0">Toutes les régions</option>
            {% set region_id = null %}
            {% for id, region in regions %}
                <option value="{{ id }}">{{ region }}</option>
                {% set region_id = id %}
            {% endfor %}
        </select>

        <select name="department" id="department-phenological-chart" class="criteria-list">
            <option value="0">Tous les départements</option>
            {% set dpt_id = null %}
            {% for id, department in departments %}
                <option value="{{ id }}">{{ department }}</option>
                {% set dpt_id = id %}
            {% endfor %}
        </select>

        <div id="alerte_pheno" class="no-data alert alert-danger">Aucune donnée pour les critères demandés, veuillez modifier au
            moins un de vos critères</div>
        <div id='nb_obs'></div>
        <div id='chart' class="chart"></div>
    </div>

    {% include 'layout/header.html.twig' with ({
        'title': 'Calendrier phénologique par espèce'
    }) %}

    <div id="phenological-chart2-container">
        <select name="species" id="species-phenological-chart2" class="criteria-list">
            <option value="0" class="default-criteria" selected>Toutes les espèces</option>
            {% set species_id = null %}
            {% for species in allSpecies %}
                <option value="{{ species.id }}">
                    {{ species.vernacularName }}
                {% set species_id = species.id %}
                </option>
            {% endfor %}
        </select>

        <select name="year" id="year-phenological-chart2" class="criteria-list">
            <option value="0">Toutes les années</option>
            {% set year = null %}
            {% for i in minYear..'now'|date('Y') %}*
                <option value="{{ i }}">{{ i }}</option>
                {% set year = i %}
            {% endfor %}
        </select>

        <select name="region" id="region-phenological-chart2" class="criteria-list">
            <option value="0">Toutes les régions</option>
            {% set region_id = null %}
            {% for id, region in regions %}
                <option value="{{ id }}">{{ region }}</option>
                {% set region_id = id %}
            {% endfor %}
        </select>

        <select name="department" id="department-phenological-chart2" class="criteria-list">
            <option value="0">Tous les départements</option>
            {% set dpt_id = null %}
            {% for id, department in departments %}
                <option value="{{ id }}">{{ department }}</option>
                {% set dpt_id = id %}
            {% endfor %}
        </select>

        <div id="alerte_pheno2" class="no-data alert alert-danger">Aucune donnée pour les critères demandés, veuillez modifier au
            moins un de vos critères</div>
        <div id='nb_obs'></div>
        <div id='chart2'></div>
    </div>

    {% include 'layout/header.html.twig' with ({
        'title': 'Évolution des stades par espèce'
    }) %}

    <div id="evolution-chart-container"  data-min-year="{{ minYear }}">
        <select name="species" id="species-evolution-chart" class="criteria-list">
            <option value="0" class="default-criteria" disabled>Choisissez une espèce</option>
            {% for species in allSpecies %}
                <option
                        value="{{ species.id }}"
                        data-events-ids="{{ speciesEvents[species.id] }}"
                        {% if 'Marronnier' == species.vernacularName %} selected{% endif %}
                >
                    {{ species.vernacularName }}
                </option>
            {% endfor %}
        </select>
        <select name="event" id="event-evolution-chart" class="criteria-list">
            <option value="0" class="default-criteria" disabled>Choisissez un évènement</option>
            {% for eventName, eventIds in eventsIds %}
                <option
                        value="{{ eventIds|join(',') }}"
                        {% if 'feuillaison' == eventName %} selected{% endif %}
                >
                    {{ eventName|capitalize }}
                </option>
            {% endfor %}
        </select>

        <select name="region" id="region-evolution-chart" class="criteria-list">
            <option value="0">Toutes les régions</option>
            {% for id, region in regions %}
                <option value="{{ id }}">{{ region }}</option>
            {% endfor %}
        </select>

        <select name="department" id="department-evolution-chart" class="criteria-list">
            <option value="0">Tous les départements</option>
            {% for id, department in departments %}
                <option value="{{ id }}">{{ department }}</option>
            {% endfor %}
        </select>

        <div class="no-data alert alert-danger">Aucune donnée pour les critères demandés, veuillez modifier au
            moins un de vos critères</div>
        <div class="chart"></div>
    </div>


    <script>
        let obsRoute = "{{ path('observations_for_charts') }}";
        let exportRoute = "{{ path('export_filtered')|escape('js') }}";
        let eventsEvolutionRoute = "{{ path('events_evolution')|escape('js') }}";
    </script>

{% endblock %}

templates/pages/species.html.twig
{% extends 'base.html.twig' %}
{% set headers = {
    'species': {
        'title': 'Espèces à observer',
        'subtitle': 'Toutes les espèces du programme <strong>Observatoire des saisons</strong>.'
    }
} %}

{% block main_content %}

    {% include 'components/actionbar.html.twig' with {
        actionbar: {
            'components': [
                {
                    'name': 'tabs-holder',
                    'data': {
                        'tabs': [
                            {
                                'title':'Plantes',
                                'reference': 'plantes'
                            },
                            {
                                'title':'Animaux',
                                'reference': 'animaux'
                            }
                        ]
                    }
                },
                {
                    'name': 'squared-button',
                    'data': {
                        'icon': 'export',
                        'label': 'exporter'
                    }
                }
            ]
        }
    } %}

    {% for id, accordion in setSpeciesDisplayData(allSpecies) %}
        {% include 'components/accordion-block.html.twig' with {type: accordion.type, typeSpecies: accordion.typeSpecies} %}
    {% endfor %}

{% endblock %}

templates/pages/static-page.html.twig
{% extends 'base.html.twig' %}

{% block main_content %}

	{% include 'layout/header.html.twig' with ({
        'title': title,
        'subtitle': subtitle|default
    }) %}
    {% set slug = page.slug %}
    {% if is_granted('ROLE_ADMIN')%}
        <a href="{{ path('admin_static_page_edit',{slug: slug}) }}" >Modifier l'article</a>
    {% endif %}
    <div class="rich-text-block">
        {{ page.content|default|raw }}
    </div>

{% endblock %}

templates/pages/stations-search.html.twig
{% extends 'pages/stations.html.twig' %}

{% block stations_grid_cards %}
	<h3 class="search-results">Résultats de votre recherche</h3>

	{% if stationsArray is empty %}
		<p class="search-results">Aucun résultat pour <strong>"{{ search }}"</strong>.</p>

	{% else %}
		<p class="search-results">
			Votre recherche correspond aux stations suivantes,<br>
			les titres correspondent aux critères de recherche :
		</p>

		{% set transSearchKey = {
			'name' : 'Nom de station',
			'locality' : 'Commune',
			'department' : 'Numéro de département',
			'displayName' : 'Nom du créateur'
		} %}
		{% for searchKey, stations in stationsArray %}
			<h4 class="search-results">{{ transSearchKey[searchKey]|capitalize }} :</h4>
			<div class="cards-grid-container">

				{% set cards = setStationCards(stations) %}
				{%  for card in cards %}
					{% include 'components/cards/station-cards.html.twig' with {
						station: card.station,
						observations: card.observations,
						contributorsCount: card.contributorsCount

					} %}
				{% endfor %}
			</div>
		{% endfor %}
	{% endif %}
	{%  if 3 > search|length and not (search matches '/^\\d+$/')%}
		<p class="search-results ods-form-warning">
			Lorsque vous utilisez moins de 3 caractères la recherche est limitée aux résultats exacts.<br>
			Pour plus de resultats (s’il en existe) veuillez entrer au moins 3 caractères.
		</p>
	{% endif %}
{% endblock %}
{% block bottom_content %}{% endblock %}